services:
  - type: web
    name: smart-breadcrumbs
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: HOST
        value: https://breadcrumb-app.onrender.com
      - key: SCOPES
        value: read_themes,write_themes,read_products,read_content
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /data/shopify.sqlite
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 