# This file stores configurations for your Shopify app.

name = "SmartBreadcrumbs"
client_id = "4f80dd60143fed09228c4e2fa9db52bb"
application_url = "https://breadcrumb-app.onrender.com"
embedded = true

[access_scopes]
# Read and modify themes
scopes = "read_themes,write_themes,read_products,read_content"

[auth]
redirect_urls = [
  "https://breadcrumb-app.onrender.com/auth/callback",
  "https://breadcrumb-app.onrender.com/auth/shopify/callback",
  "https://breadcrumb-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "breadcrumb-app.myshopify.com" 