name = "Smart Breadcrumbs"
version = "2.1.0"
type = "theme"

[settings]
  [[settings.input]]
    key = "fontSize"
    type = "number"
    label = "Font Size (px)"
    default = 14
    
  [[settings.input]]
    key = "marginTop"
    type = "number"
    label = "Margin Top (px)"
    default = 20
    
  [[settings.input]]
    key = "marginBottom"
    type = "number"
    label = "Margin Bottom (px)"
    default = 20
    
  [[settings.input]]
    key = "separator"
    type = "text"
    label = "Breadcrumb Separator"
    default = "›"
    
  [[settings.input]]
    key = "mobileSlider"
    type = "boolean"
    label = "Enable Mobile Slider"
    default = true
    
  [[settings.input]]
    key = "menuHandles"
    type = "text"
    label = "Menu Handles"
    default = "main-menu"
    info = "Comma-separated menu handles. Use * as wildcard."
    
  [[settings.input]]
    key = "customCssDesktop"
    type = "textarea"
    label = "Desktop/Tablet CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssMobile"
    type = "textarea"
    label = "Mobile CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssAll"
    type = "textarea"
    label = "All Breadcrumbs CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssLast"
    type = "textarea"
    label = "Last Breadcrumb CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssHover"
    type = "textarea"
    label = "Hover State CSS"
    default = ""

[[extensions]]
name = "Smart Breadcrumbs"
handle = "smart-breadcrumbs"
type = "theme"

[settings]
  [[settings.fields]]
  key = "font_size"
  type = "number"
  name = "Font Size"
  description = "Font size in pixels"
  default = 14

  [[settings.fields]]
  key = "margin_top"
  type = "number"
  name = "Margin Top"
  description = "Top margin in pixels"
  default = 20

  [[settings.fields]]
  key = "margin_bottom"
  type = "number"
  name = "Margin Bottom"
  description = "Bottom margin in pixels"
  default = 20

  [[settings.fields]]
  key = "separator"
  type = "text"
  name = "Breadcrumb Separator"
  description = "Character or HTML to separate breadcrumb items"
  default = "›"

  [[settings.fields]]
  key = "mobile_slider"
  type = "boolean"
  name = "Enable Mobile Slider"
  description = "Enable horizontal scrolling on mobile devices"
  default = true 