name = "Smart Breadcrumbs"
version = "5.1.0"
type = "theme"
handle = "smart-breadcrumbs"

# Theme extension settings
[[extensions]]
type = "section"
name = "Smart Breadcrumbs"
handle = "breadcrumbs"
template = ["index", "product", "collection", "page", "cart", "blog", "article"]

[[assets]]
type = "script"
handle = "breadcrumb-helper"
path = "assets/breadcrumb-helper.js"
load = "defer"
includes = ["product"]

[[settings]]
  [[settings.input]]
    key = "fontSize"
    type = "number"
    label = "Font Size (px)"
    default = 14
    
  [[settings.input]]
    key = "marginTop"
    type = "number"
    label = "Margin Top (px)"
    default = 20
    
  [[settings.input]]
    key = "marginBottom"
    type = "number"
    label = "Margin Bottom (px)"
    default = 20
    
  [[settings.input]]
    key = "separator"
    type = "text"
    label = "Breadcrumb Separator"
    default = "›"
    
  [[settings.input]]
    key = "mobileSlider"
    type = "boolean"
    label = "Enable Mobile Slider"
    default = true
    
  [[settings.input]]
    key = "menuHandles"
    type = "text"
    label = "Menu Handles"
    default = "main-menu"
    info = "Comma-separated menu handles. Use * as wildcard."
    
  [[settings.input]]
    key = "customCssDesktop"
    type = "textarea"
    label = "Desktop/Tablet CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssMobile"
    type = "textarea"
    label = "Mobile CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssAll"
    type = "textarea"
    label = "All Breadcrumbs CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssLast"
    type = "textarea"
    label = "Last Breadcrumb CSS"
    default = ""
    
  [[settings.input]]
    key = "customCssHover"
    type = "textarea"
    label = "Hover State CSS"
    default = ""

[settings]
  [[settings.fields]]
  type = "checkbox"
  id = "use_menu_based_breadcrumbs"
  label = "Use menu-based breadcrumbs"
  info = "Generate breadcrumbs based on menu structure (recommended for better SEO)"
  default = true

  [[settings.fields]]
  type = "checkbox"
  id = "show_breadcrumbs"
  label = "Show breadcrumbs"
  default = true

  [[settings.fields]]
  type = "checkbox"
  id = "use_slider_for_mobile"
  label = "Use slider for mobile"
  info = "On mobile, breadcrumbs become a slider instead of wrapping"
  default = false

  [[settings.fields]]
  type = "color"
  id = "breadcrumb_background_color"
  label = "Background color"
  default = "rgba(240, 240, 240, 0.5)"

  [[settings.fields]]
  type = "select"
  id = "breadcrumb_alignment"
  label = "Alignment"
  [[settings.fields.options]]
  value = "left"
  label = "Left"
  [[settings.fields.options]]
  value = "center"
  label = "Center"
  [[settings.fields.options]]
  value = "right"
  label = "Right"
  default = "left"

  [[settings.fields]]
  type = "range"
  id = "breadcrumb_font_size"
  label = "Font size"
  min = 10
  max = 24
  step = 1
  unit = "px"
  default = 14

  [[settings.fields]]
  type = "text"
  id = "breadcrumb_font_family"
  label = "Font family"
  info = "Leave blank to use theme default"

  [[settings.fields]]
  type = "text"
  id = "breadcrumb_home_text"
  label = "Home link text"
  default = "Home"

  [[settings.fields]]
  type = "color"
  id = "breadcrumb_text_color"
  label = "Text color"
  default = "#555555"

  [[settings.fields]]
  type = "color"
  id = "breadcrumb_hover_color"
  label = "Hover color"
  default = "#000000"

  [[settings.fields]]
  type = "color"
  id = "breadcrumb_separator_color"
  label = "Separator color"
  default = "#999999"

  [[settings.fields]]
  type = "color"
  id = "breadcrumb_current_color"
  label = "Current item color"
  default = "#333333"

  [[settings.fields]]
  type = "checkbox"
  id = "breadcrumb_use_uppercase"
  label = "Use uppercase text"
  default = false

# Extension assets
[[files]]
handle = "breadcrumbs.css"
path = "assets/breadcrumbs.css"

[[files]]
handle = "breadcrumbs.js"
path = "assets/breadcrumbs.js"

[[files]]
handle = "breadcrumb-settings.js"
path = "assets/breadcrumb-settings.js"

[[files]]
handle = "menu-parser.js"
path = "assets/menu-parser.js"

[[files]]
handle = "breadcrumb-client.js"
path = "assets/breadcrumb-client.js"

# Extension snippets
[[files]]
handle = "smart-breadcrumbs"
path = "snippets/smart-breadcrumbs.liquid"

[[files]]
handle = "smart-breadcrumbs-product"
path = "snippets/smart-breadcrumbs-product.liquid"

[[files]]
handle = "smart-breadcrumbs-collection"
path = "snippets/smart-breadcrumbs-collection.liquid"

[[files]]
handle = "smart-breadcrumbs-page"
path = "snippets/smart-breadcrumbs-page.liquid"

# Extension blocks
[[files]]
handle = "breadcrumbs"
path = "blocks/breadcrumbs.liquid"

# Extension sections
[[files]]
handle = "settings"
path = "sections/settings.liquid" 