name = "Smart Breadcrumbs"
version = "2.0.0"
type = "theme"

[settings]
  [[settings.input]]
    key = "breadcrumb_font_size"
    type = "number"
    label = "Font Size (px)"
    default = 14
    
  [[settings.input]]
    key = "breadcrumb_mobile_font_size"
    type = "number"
    label = "Mobile Font Size (px)"
    default = 12
    
  [[settings.input]]
    key = "breadcrumb_color"
    type = "color"
    label = "Text Color"
    default = "#666666"
    
  [[settings.input]]
    key = "breadcrumb_hover_color"
    type = "color"
    label = "Hover Color"
    default = "#000000"
    
  [[settings.input]]
    key = "breadcrumb_separator_color"
    type = "color"
    label = "Separator Color"
    default = "#999999"
    
  [[settings.input]]
    key = "breadcrumb_current_color"
    type = "color"
    label = "Current Page Color"
    default = "#333333"
    
  [[settings.input]]
    key = "enable_mobile_slider"
    type = "boolean"
    label = "Enable Mobile Slider"
    default = true
    
  [[settings.input]]
    key = "menu_handles"
    type = "text"
    label = "Menu Handles"
    default = "main-menu"
    info = "Comma-separated menu handles. Use * as wildcard."

[[extensions]]
name = "Smart Breadcrumbs"
handle = "smart-breadcrumbs"
type = "theme"

[settings]
  [[settings.fields]]
  key = "font_size"
  type = "number"
  name = "Font Size"
  description = "Font size in pixels"
  default = 14

  [[settings.fields]]
  key = "margin_top"
  type = "number"
  name = "Margin Top"
  description = "Top margin in pixels"
  default = 20

  [[settings.fields]]
  key = "margin_bottom"
  type = "number"
  name = "Margin Bottom"
  description = "Bottom margin in pixels"
  default = 20

  [[settings.fields]]
  key = "separator"
  type = "text"
  name = "Breadcrumb Separator"
  description = "Character or HTML to separate breadcrumb items"
  default = "›"

  [[settings.fields]]
  key = "mobile_slider"
  type = "boolean"
  name = "Enable Mobile Slider"
  description = "Enable horizontal scrolling on mobile devices"
  default = true 